version: "3"

services:
  fin_api:
    image: postgres
    container_name: fin_api_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/postgres
    networks:
      - backend
  api:
    build: .
    container_name: app
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local

networks:
  backend:
    driver: "bridge"
